In [2]:
import torch
import numpy as np

In [3]:
torch.cuda.is_available()

True

## Check for gpu

In [4]:
!nvidia-smi

Wed May 10 20:08:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
some_data = [[1, 2], [3, 4]]

In [6]:
some_data

[[1, 2], [3, 4]]

In [7]:
type(some_data)

list

In [8]:
## Convert to array
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

Both the above two commands perform the same operation of converting data to numpy array.

## Converting the above array to torch tensor

In [10]:
some_data = torch.tensor(some_data)

In [11]:
type(some_data)

torch.Tensor

In [12]:
some_data.dtype

torch.int64

## Create a random array of 3 rows and 4 columns

In [13]:
numpy_array = np.random.rand(3,4)

In [14]:
numpy_array

array([[0.98939467, 0.21751483, 0.64916102, 0.39560849],
       [0.61694067, 0.84954638, 0.13907573, 0.157693  ],
       [0.39605597, 0.45646569, 0.09282762, 0.1102856 ]])

## To change to torch tensor

In [15]:
torch.from_numpy(numpy_array)

## torch.tensor(numpy_array) will also perform the same function

tensor([[0.9894, 0.2175, 0.6492, 0.3956],
        [0.6169, 0.8495, 0.1391, 0.1577],
        [0.3961, 0.4565, 0.0928, 0.1103]], dtype=torch.float64)

## To create array with all ones in it

In [16]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensors are arrays stored on CPU or GPU memory. Any operations done on tensor arrays will be on CPU or GPU as specified.

## Generate matrix of random numbers using torch

In [18]:
my_tensor = torch.rand(3,4)
my_tensor

tensor([[0.4903, 0.9470, 0.7538, 0.9997],
        [0.5561, 0.2982, 0.7870, 0.6873],
        [0.8973, 0.6198, 0.5160, 0.1863]])

In [19]:
my_tensor.dtype

torch.float32

## Checking where my tensor array resides and moving to GPU

In [24]:
my_tensor.device

device(type='cuda', index=0)

In [23]:
my_tensor = my_tensor.to("cuda")

## Element wise multiplication

In [25]:
mt1 = my_tensor.mul(my_tensor)
mt1

tensor([[0.2404, 0.8969, 0.5682, 0.9995],
        [0.3092, 0.0889, 0.6194, 0.4723],
        [0.8052, 0.3841, 0.2662, 0.0347]], device='cuda:0')

In [26]:
mt2 = my_tensor * my_tensor
mt2

tensor([[0.2404, 0.8969, 0.5682, 0.9995],
        [0.3092, 0.0889, 0.6194, 0.4723],
        [0.8052, 0.3841, 0.2662, 0.0347]], device='cuda:0')

## Matrix multiplication

In [28]:
my_tensor.matmul(my_tensor.T) # .T means transpose of the matric

tensor([[2.7049, 1.8353, 1.6021],
        [1.8353, 1.4898, 1.2179],
        [1.6021, 1.2179, 1.4903]], device='cuda:0')

In [29]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[2.7049, 1.8353, 1.6021],
        [1.8353, 1.4898, 1.2179],
        [1.6021, 1.2179, 1.4903]], device='cuda:0')

In [30]:
my_tensor @ my_tensor.T

tensor([[2.7049, 1.8353, 1.6021],
        [1.8353, 1.4898, 1.2179],
        [1.6021, 1.2179, 1.4903]], device='cuda:0')

## Sum of elements

In [31]:
my_tensor.sum()

tensor(7.7388, device='cuda:0')

In [32]:
my_tensor.sum(axis=1) # Along the column

tensor([3.1908, 2.3285, 2.2194], device='cuda:0')

In [33]:
my_tensor.sum(axis=0) # Along the rows

tensor([1.9437, 1.8650, 2.0568, 1.8733], device='cuda:0')

## Concat two tensors

Concats two tensors

In [37]:
torch.cat([my_tensor, my_tensor], axis = 0) # dim can also be used in place of axis

tensor([[0.4903, 0.9470, 0.7538, 0.9997],
        [0.5561, 0.2982, 0.7870, 0.6873],
        [0.8973, 0.6198, 0.5160, 0.1863],
        [0.4903, 0.9470, 0.7538, 0.9997],
        [0.5561, 0.2982, 0.7870, 0.6873],
        [0.8973, 0.6198, 0.5160, 0.1863]], device='cuda:0')

## Softmax

dim = 0 -> gives the result such that sum of the columns is 1

dim = 1 -> gives the result such that sum of the rows is 1

In [38]:
torch.nn.functional.softmax(my_tensor, dim=0)

tensor([[0.2801, 0.4457, 0.3543, 0.4598],
        [0.2991, 0.2330, 0.3663, 0.3364],
        [0.4208, 0.3213, 0.2794, 0.2038]], device='cuda:0')

## Get the dimensions of the tensor array

In [39]:
my_tensor.shape

torch.Size([3, 4])

In [40]:
my_tensor.size()

torch.Size([3, 4])

## Clip the tensor array

In [42]:
my_tensor

tensor([[0.4903, 0.9470, 0.7538, 0.9997],
        [0.5561, 0.2982, 0.7870, 0.6873],
        [0.8973, 0.6198, 0.5160, 0.1863]], device='cuda:0')

In [41]:
# anything above 0.8 will be converted to 0.8 and anything below 0.2 will be changed to 0.2
my_tensor.clip(0.2, 0.8)

tensor([[0.4903, 0.8000, 0.7538, 0.8000],
        [0.5561, 0.2982, 0.7870, 0.6873],
        [0.8000, 0.6198, 0.5160, 0.2000]], device='cuda:0')

## Convert tensor array to numpy array

In [43]:
# bring to cpu, detach from cpu, convert to numpy
my_tensor.cpu().detach().numpy()

array([[0.49027777, 0.9470292 , 0.7537696 , 0.99972874],
       [0.55607873, 0.29819685, 0.78699833, 0.68726873],
       [0.89734614, 0.6197923 , 0.51599157, 0.1862737 ]], dtype=float32)

## Other Functions

torch.max
torch.min