In [2]:
import torch

## Declare variable

In [4]:
a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)

In [5]:
a

tensor([5.], requires_grad=True)

In [6]:
b

tensor([6.], requires_grad=True)

In [7]:
y = a**3 - b**2

In [8]:
y

tensor([89.], grad_fn=<SubBackward0>)

## Calculating loss

dy/da = 3 * (a**2) = 3 *   5 * 5 = 75

dy/db = -2b = -2 * 6 = -12

a.grad and b.grad will give the gradient of the variable a and b. Before performing the gradient, we have to execute backward() on y.

In [9]:
y.backward()

In [10]:
a.grad

tensor([75.])

In [11]:
b.grad

tensor([-12.])

In [12]:
W = torch.randn(10, 1, requires_grad = True)
b = torch.randn(1, requires_grad = True)

In [13]:
W

tensor([[-0.7035],
        [-1.2850],
        [-0.0133],
        [-0.0103],
        [-1.2961],
        [ 0.8783],
        [-0.6677],
        [ 1.5291],
        [ 0.4766],
        [-0.0082]], requires_grad=True)

In [15]:
x = torch.randn(1, 10)

In [16]:
x

tensor([[ 0.8046, -0.5827, -1.8379, -0.5797, -0.7992,  0.9646,  0.4329, -0.5261,
          0.0729, -1.5324]])

In [17]:
output = torch.matmul(x, W) + b

In [18]:
loss = 1 - output

In [19]:
loss

tensor([[-1.6147]], grad_fn=<RsubBackward1>)

In [20]:
output

tensor([[2.6147]], grad_fn=<AddBackward0>)

In [21]:
loss.backward()

In [23]:
W.grad

tensor([[-0.8046],
        [ 0.5827],
        [ 1.8379],
        [ 0.5797],
        [ 0.7992],
        [-0.9646],
        [-0.4329],
        [ 0.5261],
        [-0.0729],
        [ 1.5324]])

In [24]:
b.grad

tensor([-1.])

## Update the weights

In [25]:
with torch.no_grad():
    W = W - 0.001 * W.grad.data

In [26]:
W

tensor([[-0.7027],
        [-1.2856],
        [-0.0152],
        [-0.0109],
        [-1.2969],
        [ 0.8793],
        [-0.6673],
        [ 1.5286],
        [ 0.4766],
        [-0.0097]])