In [9]:
# nn.Module - base class for neural network modules

import torch
import torch.nn as nn

In [10]:
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    ## Define the layers
    self.layer1 = nn.Linear(128, 32) # i/p and o/p for the layer
    self.layer2 = nn.Linear(32, 16)
    self.layer3 = nn.Linear(16, 1)
  
  def forward(self, features):
    # input = (32, 128)
    x = self.layer1(features) # (32, 32)
    print(x.shape)
    x = self.layer2(x)
    x = self.layer3(x) #(32,1)
    return x

In [11]:
model = Model()
features = torch.rand(2, 128) # 2 samples of 128 features each
print(features)

tensor([[7.1785e-01, 3.0715e-01, 7.4500e-01, 8.7050e-02, 7.0203e-01, 2.8629e-01,
         5.4384e-02, 7.3192e-01, 9.9132e-01, 8.7862e-01, 3.9889e-01, 3.3539e-01,
         3.6932e-01, 8.1527e-02, 3.9305e-01, 5.2936e-01, 8.7396e-01, 6.1016e-01,
         5.0060e-01, 9.3523e-02, 5.6001e-01, 1.2756e-01, 3.6780e-01, 1.8677e-01,
         3.5293e-01, 3.3044e-01, 6.3215e-01, 4.4571e-01, 2.7731e-01, 7.6517e-01,
         1.5078e-02, 6.6799e-01, 8.1407e-01, 3.3100e-01, 4.3118e-01, 4.1188e-01,
         5.3604e-02, 6.2597e-01, 4.0414e-03, 1.0191e-01, 9.1235e-01, 4.3379e-01,
         3.5992e-01, 7.8973e-01, 9.4796e-01, 1.7839e-01, 8.2060e-01, 6.2046e-01,
         7.7690e-01, 3.0514e-01, 9.0208e-01, 6.9558e-01, 5.3467e-02, 5.9833e-01,
         2.6023e-01, 8.8544e-01, 1.6512e-01, 3.8830e-01, 8.8057e-01, 1.0593e-01,
         1.3892e-02, 3.1182e-01, 6.6653e-01, 3.4013e-02, 6.0863e-01, 1.0169e-01,
         2.6277e-01, 6.8109e-01, 7.1525e-02, 8.2316e-02, 5.0534e-01, 8.9525e-01,
         9.2301e-01, 5.5821e

In [12]:
model(features)

torch.Size([2, 32])


tensor([[ 0.0280],
        [-0.0776]], grad_fn=<AddmmBackward0>)

In [13]:
features.device

device(type='cpu')

In [14]:
features = features.to("cuda")
model = Model()
model.to("cuda")
model(features)

torch.Size([2, 32])


tensor([[0.3481],
        [0.2780]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [15]:
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    ## Define the base layer
    self.base = nn.Sequential(
    nn.Linear(128, 32), # layers will be applied sequentially
    nn.Linear(32, 16),
    nn.Linear(16, 1)
)
    
  
  def forward(self, features):
    # input = (32, 128)
    x = self.base(features) # (32, 1)
    #print(x.shape)
    return x

In [16]:
features = features.to("cuda")
model = Model()
model.to("cuda")
model(features)

tensor([[-0.0684],
        [-0.2144]], device='cuda:0', grad_fn=<AddmmBackward0>)